spring.application.name=CvMaker

spring.datasource.url=jdbc:postgresql://localhost:5432/CvMaker
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
spring.jpa.show-sql=true


logging.level.org.springframework.security=DEBUG

# Hugging Face API Key (Replace with your actual key)
huggingface.api.key=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
huggingface.api.url=https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3