spring.application.name=CvMaker
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:cvdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hugging Face API Key (Replace with your actual key)
huggingface.api.key=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
huggingface.api.url=https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3